-- MySQL Script generated by MySQL Workbench (исправленная версия)
-- Model: mydb    Version: 1.1

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb4;
USE `mydb`;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `users_id` INT NOT NULL AUTO_INCREMENT,
  `users_email` VARCHAR(155) NOT NULL,
  `user_password_hash` VARCHAR(255) NOT NULL,  
  PRIMARY KEY (`users_id`),
  UNIQUE INDEX `users_email_UNIQUE` (`users_email` ASC) VISIBLE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categories` ;
CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `categories_id` INT NOT NULL AUTO_INCREMENT,
  `categories_name` VARCHAR(100) NOT NULL,
  `categories_slug` VARCHAR(100) NOT NULL,
  `categories_parent_id` INT NULL,
  PRIMARY KEY (`categories_id`),
  UNIQUE INDEX `categories_name_UNIQUE` (`categories_name` ASC) VISIBLE,
  UNIQUE INDEX `categories_slug_UNIQUE` (`categories_slug` ASC) VISIBLE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`products` ;
CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `products_id` INT NOT NULL AUTO_INCREMENT,
  `products_name` VARCHAR(200) NOT NULL,
  `products_price` DECIMAL(10,2) NOT NULL,
  `products_description` VARCHAR(2000) NULL,
  `category_id` INT NOT NULL,
  `products_size` VARCHAR(10) NOT NULL,
  `products_color` VARCHAR(50) NOT NULL,
  `products_image` VARCHAR(255) NULL,
  PRIMARY KEY (`products_id`),
  INDEX `category_id_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`categories` (`categories_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`orders` ;
CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `orders_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `order_price` DECIMAL(10,2) NULL,
  `order_date` DATETIME NULL,
  PRIMARY KEY (`orders_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`orders_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`orders_products` ;
CREATE TABLE IF NOT EXISTS `mydb`.`orders_products` (
  `orders_products_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `orders_products_counts` INT NOT NULL,
  `orders_products_size` VARCHAR(10) NOT NULL,
  `orders_products_color` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`orders_products_id`),
  INDEX `order_id_idx` (`order_id` ASC) VISIBLE,
  INDEX `product_id_idx` (`product_id` ASC) VISIBLE,
  -- Составной уникальный ключ, чтобы не дублировать одну и ту же позицию в заказе
  UNIQUE INDEX `unique_order_product` (`order_id`, `product_id`, `orders_products_size`, `orders_products_color`),
  CONSTRAINT `fk_orders_products_order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`orders` (`orders_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_products_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`products` (`products_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`favorites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`favorites` ;
CREATE TABLE IF NOT EXISTS `mydb`.`favorites` (
  `favorites_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`favorites_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `product_id_idx` (`product_id` ASC) VISIBLE,
  -- Составной уникальный ключ: один пользователь может добавить товар в избранное только один раз
  UNIQUE INDEX `unique_user_product` (`user_id`, `product_id`),
  CONSTRAINT `fk_favorites_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorites_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`products` (`products_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;